### ISSUE TITLE
[Server] When a player looks at a creeper, they client crash

### ISSUE THREAD

**Issue by XionioXMaster** [Insane96/EnhancedAI#11]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/30/21 11:17 PM
Description: Ticking entity

java.lang.NullPointerException: Registry Object not present: enhancedai:creeper_cena_fuse
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge-1.16.5-36.2.2-universal.jar:?] {re:mixin,re:classloading}
	at net.minecraft.entity.monster.CreeperEntity.handler$znb000$tickOnPlaySound(CreeperEntity.java:517) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedai.mixins.json:CreeperEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:136) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedai.mixins.json:CreeperEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5-20210115.111550-slim.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) [?:1.8.0_291] {}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.mIAvZQ7yUeNTJ0(Unknown Source) [MIA.exe:?] {re:classloading}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.main(Unknown Source) [MIA.exe:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.CreeperEntity)
	Entity ID: 31847
	Entity Name: Крипер
	Entity's Exact location: -1137.29, 74.00, -449.68
	Entity's Block location: World: (-1138,74,-450), Chunk: (at 14,4,14 in -72,-29; contains blocks -1152,0,-464 to -1137,255,-449), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Brain:{memories:{}},HurtByTimestamp:0,ForgeData:{"enhancedai:john_cena":1b,"enhancedai:explosion_causes_fire":1b},Attributes:[{Base:0.0d,Name:"minecraft:generic.knockback_resistance"},{Base:0.08d,Name:"forge:entity_gravity"},{Base:0.25d,Name:"minecraft:generic.movement_speed"},{Base:20.0d,Name:"minecraft:generic.max_health"},{Base:1.0d,Name:"forge:swim_speed"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,CanUpdate:1b,DeathTime:0s,ForgeCaps:{"structure_gel:gel_entity":{portal:"structure_gel:empty"},"mowziesmobs:frozen":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,freezeDecayDelay:0,prevHasAI:1b,frozenYawHead:0.0f,frozenLimbSwingAmount:0.0f,prevFrozen:0b,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"citadel:extended_entity_data_citadel":{},"eidolon:knowledge":{signs:[],facts:[]}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,UUID:[I;137997663,-689290782,-1801375279,-814791273],Fuse:34s,Motion:[0.0d,-0.078375d,0.0d],Health:20.0f,LeftHanded:0b,Air:284s,OnGround:1b,CitadelData:{},ignited:0b,Rotation:[0.0f,0.0f],HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[-1137.2886998362503d,74.0d,-449.6819426246372d],fireType:"fire",Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s,ExplosionRadius:6b}
-- Affected level --
Details:
	All players: 3 total; [ClientPlayerEntity['Zireael'/373, l='ClientLevel', x=-1145.00, y=86.00, z=-433.96], RemoteClientPlayerEntity['AVGUR'/1003, l='ClientLevel', x=-1139.83, y=86.00, z=-431.14], RemoteClientPlayerEntity['DeZoWaRe'/1686, l='ClientLevel', x=-1137.98, y=75.18, z=-451.64]]
	Chunk stats: Client Chunk Cache: 441, 285
	Level dimension: minecraft:the_end
	Level spawn location: World: (112,70,64), Chunk: (at 0,4,0 in 7,4; contains blocks 112,0,64 to 127,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 66079 game time, 66079 day time
	Server brand: LoliServer
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28) ~[notenoughcrashes:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.modify$zzh000$onCrash(Minecraft.java:2548) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5-20210115.111550-slim.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) [?:1.8.0_291] {}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.mIAvZQ7yUeNTJ0(Unknown Source) [MIA.exe:?] {re:classloading}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.main(Unknown Source) [MIA.exe:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 496919480 bytes (473 MB) / 2040791040 bytes (1946 MB) up to 2040791040 bytes (1946 MB)
	CPUs: 4
	JVM Flags: 16 total; -XX:+AggressiveOpts -XX:+UseStringCache -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseFastAccessorMethods -XX:SoftRefLRUPolicyMSPerMB=1 -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn538M -XX:+DisableAttachMechanism -Xms2000M -Xmx2000M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.14.0
	Mod List: 
		create-stuff-additions1.16.5_v1.0.6.jar           |Create Stuff Additions        |create_stuff_additions        |1.0.6               |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-3.2.0-forge.jar                  |Not Enough Crashes            |notenoughcrashes              |3.2.0               |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-2.2.0.jar                      |Infernal Expansion            |infernalexp                   |2.2.0               |DONE      |Manifest: NOSIGNATURE
		Pirates_And_Looters_Kraken_Update.jar             |PiratesAndLootersReborn       |piratesandlootersreborn       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		nether-s-exoticism-1.16.5-1.1.1.jar               |Nether's Exoticism            |nethers_exoticism             |1.1.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.118.jar                          |Just Enough Items             |jei                           |7.7.1.118           |DONE      |Manifest: NOSIGNATURE
		Druidcraft-1.16.5-0.4.52.jar                      |Druidcraft                    |druidcraft                    |0.4.52              |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.16.4-1.0.13.jar                    |The Conjurer                  |conjurer_illager              |1.0.13              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.2.0.jar                   |Abnormals Core                |abnormals_core                |3.2.0               |DONE      |Manifest: NOSIGNATURE
		Kobolds-1.4.3.jar                                 |Kobolds                       |kobolds                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.2.1-mc1.16.5.jar                      |InsaneLib                     |insanelib                     |1.2.1-mc1.16.5      |DONE      |Manifest: NOSIGNATURE
		etched-1.1.0-1.16.5-forge.jar                     |Etched                        |etched                        |1.1.0               |DONE      |Manifest: NOSIGNATURE
		ravageandcabbage-1.0.0.jar                        |Ravage & Cabbage              |ravageandcabbage              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		village-employment-1.16.5-1.4.1.jar               |Village Employment            |village_employment            |1.4.1               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.0-1.16.5.jar                          |Citadel                       |citadel                       |1.8.0               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.0              |DONE      |Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.0.jar                    |Environmental                 |environmental                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		[1.16.5]-Epic-Knights-Armor-and-Weapons-1.9v.jar  |Epic Knights Armor and Weapons|magistuarmory                 |1.16-1.17           |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		catalogue-1.3.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.4.1.jar                       |iChunUtil                     |ichunutil                     |10.4.1              |DONE      |Manifest: NOSIGNATURE
		chat_heads_forge-0.2.0.jar                        |Chat Heads                    |chat_heads                    |0.2.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		supplementaries-1.16.5-0.15.2b.jar                |Supplementaries               |supplementaries               |1.16.5-0.15.0       |DONE      |Manifest: NOSIGNATURE
		playereatinganimation-1.2.jar                     |Player Eating Animation       |playereatinganimation         |1.2                 |DONE      |Manifest: NOSIGNATURE
		konkrete_1.1.6_MC_1.16.2-1.16.5.jar               |Konkrete                      |konkrete                      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |Manifest: NOSIGNATURE
		Upgraded+Netherite+1.10.0.jar                     |Upgraded Netherite            |upgradednetherite             |1.10.0              |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.6.jar                             |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.16.5-1.2.5.jar               |Advancement Plaques           |advancementplaques            |1.2.5               |DONE      |Manifest: NOSIGNATURE
		Abyss-Render.jar                                  |Abyss-Render                  |out_of_sight                  |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.6.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.6        |DONE      |Manifest: NOSIGNATURE
		customizableelytra-1.16.4-1.5.5.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.5.5        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.4.jar              |More Villagers                |morevillagers                 |1.5.4               |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v3.1.9_mc1.16.5.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		EntityCulling-1.16.5-2.1.6.jar                    |Entity Culling                |entity_culling                |2.1.6               |DONE      |Manifest: NOSIGNATURE
		endremastered-forge-R4.1.jar                      |End Remastered                |endrem                        |4.1                 |DONE      |Manifest: NOSIGNATURE
		scarecrowsterritory-1.1.2-mc1.16.jar              |Scarecrow's Territory         |scarecrowsterritory           |1.1.2               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.12-mc1.16.5.jar        |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.12              |DONE      |Manifest: NOSIGNATURE
		atmospheric-1.16.5-3.1.0.jar                      |Atmospheric                   |atmospheric                   |3.1.0               |DONE      |Manifest: NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |Manifest: NOSIGNATURE
		decorative_winter-0.1.2.jar                       |Decorative Winter             |decorative_winter             |0.1.2               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.3.jar                           |Flywheel                      |flywheel                      |1.16-0.2.3          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		eidolon-0.3_Made_In_Abyss_Server.jar              |Eidolon Made In Abyss Server F|eidolon                       |0.3                 |DONE      |Manifest: NOSIGNATURE
		Atum-1.16.5-2.2.7.jar                             |Atum 2                        |atum                          |1.16.5-2.2.7        |DONE      |Manifest: NOSIGNATURE
		omnis-1.16.5-1.1.2.3.jar                          |Omnis                         |omnis                         |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.1.jar                         |Patchouli                     |patchouli                     |1.16.4-53.1         |DONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.16.5-1.2.0.jar                |Abnormals Delight             |abnormals_delight             |1.2.0               |DONE      |Manifest: NOSIGNATURE
		DiagonalFences-v1.1.1-1.16.5.jar                  |Diagonal Fences               |diagonalfences                |1.1.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		twoplayersonehorse-1.16.4-2.0.2.jar               |2 players 1 horse             |twoplayersonehorse            |1.16.4-2.0.2        |DONE      |Manifest: NOSIGNATURE
		simplytea-1.16.5-2.4.0.jar                        |Simply Tea                    |simplytea                     |2.4.0               |DONE      |Manifest: NOSIGNATURE
		EnigmaticLegacy-2.11.4.jar                        |Enigmatic Legacy              |enigmaticlegacy               |2.11.4              |DONE      |Manifest: NOSIGNATURE
		fancymenu_2.2.2_MC_1.16.2-1.16.5.jar              |FancyMenu                     |fancymenu                     |2.2.2               |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.16.5-1.4.0.jar                    |Hunter Illager                |hunterillager                 |1.16.5-1.4.0        |DONE      |Manifest: NOSIGNATURE
		nethers_delight-2.1.jar                           |Nethers Delight               |nethers_delight               |2.1                 |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.1.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.1.0      |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.0.7-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.7               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		BackTools-1.16.5-10.1.0.jar                       |Back Tools                    |backtools                     |10.1.0              |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.10-1.16.5.jar                     |Puzzles Lib                   |puzzleslib                    |1.0.10              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		EnhancedAI-1.1.0-mc1.16.5.jar                     |Enhanced AI                   |enhancedai                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		smallships-1.16.5-1.10.1.jar                      |Small Ships Mod               |smallships                    |1.10.1              |DONE      |Manifest: NOSIGNATURE
		farmerstea-1.16.5-1.2.jar                         |Farmer's Tea                  |farmerstea                    |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.4.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.4        |DONE      |Manifest: NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 571a6775-a3cc-41b1-b552-cbd3ea56ab02
	Patchouli open book context: n/a
	Suspected Mods: Forge (forge)
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon R7 200 Series GL version 4.6.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, file/Ryans 32x Lower Fire.zip (incompatible), file/Water Improved.zip (incompatible), file/Pixel Reality Atmosphere.zip, file/Pixel Reality Luminance.zip
	Current Language: Русский (Россия)
	CPU: <unknown>
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Insane96** [comment]
Please reopen the issue with the new issue template, thank you.
