### ISSUE TITLE
Crash to server side new Alpha version

### ISSUE THREAD

**Issue by XionioXMaster** [Insane96/EnhancedAI#21]
Time: 9/26/21, 12:02 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66) [server.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63) [server.jar:?] {}
at net.minecraftforge.server.ServerMain.main(ServerMain.java:60) [server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[server.jar:36.1] {}
-- MOD enhancedai --
Details:
at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {} at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[server.jar:36.1] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
at insane96mcp.enhancedai.EnhancedAI.<init>(EnhancedAI.java:20) ~[enhancedai:Alpha-1.2.0] {re:classloading}
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading} at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.1] {re:classloading}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
CPUs: 6

Java Version: 11.0.12, GraalVM Community
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), GraalVM Community
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading}
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER
at insane96mcp.enhancedai.EnhancedAI.<init>(EnhancedAI.java:20) ~[enhancedai:Alpha-1.2.0] {re:classloading}

at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}

at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}

Mod File: EnhancedAI-Alpha-1.2.0-mc1.16.5.jar
Mod Version: Alpha-1.2.0 Failure message: Enhanced AI (enhancedai) has failed to load correctlyjava.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}

Mod Issue URL: https://github.com/Insane96/EnhancedAI/issues
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {} Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/entity/EntityRenderer for invalid dist DEDICATED_SERVER
Stacktrace:

at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}

at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}

Minecraft Version: 1.16.5-- System Details --
Details:

LoliServer Version: 1.16.5-90
Minecraft Version ID: 1.16.5
Operating System: Linux (amd64) version 5.4.0-29-generic
Memory: 10141977216 bytes (9672 MB) / 12901679104 bytes (12304 MB) up to 12901679104 bytes (12304 MB)JVM Flags: 28 total; -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:ThreadPriorityPolicy=1 -Xms12300M -Xmx12300M -XX:+UseThrea
ModLauncher launch target: fmlserver
ModLauncher naming: srg
ModLauncher services:
/mixin-0.8.4.jar mixin PLUGINSERVICE
dPriorities -XX:+UseBiasedLocking -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:InitiatingHeapOccupancyPercent=20
ModLauncher: 8.0.9+86+master.3cf110c /server.jar object_holder_definalize PLUGINSERVICE /eventbus-4.0.0.jar eventbus PLUGINSERVICE
/server.jar runtime_enum_extender PLUGINSERVICE /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
/server.jar capability_inject_definalize PLUGINSERVICE

/server.jar runtimedistcleaner PLUGINSERVICE /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE
/server.jar fml TRANSFORMATIONSERVICE FML: 36.1
Forge: net.minecraftforge:36.2.5
FML Language Providers:
javafml@36.1
minecraft@1
kotlinforforge@1.14.0
Mod List:
create-stuff-additions1.16.5_v1.0.9.jar |Create Stuff Additions |create_stuff_additions |1.0.9 |CREATE_REG|Manifest: NOSIGNATURE
mowziesmobs-1.5.19.jar |Mowzie's Mobs |mowziesmobs |1.5.19 |CREATE_REG|Manifest: NOSIGNATURE
BetterDungeons-1.16.4-1.2.jar |YUNG's Better Dungeons |betterdungeons |1.16.4-1.2 |CREATE_REG|Manifest: NOSIGNATURE
infernal-expansion-2.3.1.jar |Infernal Expansion |infernalexp |2.3.1 |CREATE_REG|Manifest: NOSIGNATURE
CustomSkinLoader_ForgeLegacy-14.13-SNAPSHOT-282.ja|CustomSkinLoader |customskinloader |14.13-SNAPSHOT-282 |CREATE_REG|Manifest: 4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54
jei-1.16.5-7.7.1.121.jar |Just Enough Items |jei |7.7.1.121 |CREATE_REG|Manifest: NOSIGNATURE
druidcraft-1.16.5-0.4.52-patched.jar |Druidcraft |druidcraft |0.4.52 |CREATE_REG|Manifest: NOSIGNATURE
the-conjurer-1.16.4-1.0.13.jar |The Conjurer |conjurer_illager |1.0.13 |CREATE_REG|Manifest: NOSIGNATURE

abnormals_core-1.16.5-3.3.0.jar |Abnormals Core |abnormals_core |3.3.0 |CREATE_REG|Manifest: NOSIGNATURE
justmobheads_1.16.5-4.1.jar |Just Mob Heads |justmobheads |4.1 |CREATE_REG|Manifest: NOSIGNATURE
BetterNether-PR_2.jar |Better Nether Reforged |betternether |1.0 |CREATE_REG|Manifest: NOSIGNATURE
strawgolem-1.16-1.9.jar |Straw Golem |strawgolem |1.16-1.9 |CREATE_REG|Manifest: NOSIGNATURE
Kobolds-1.4.5.jar |Kobolds |kobolds |1.0.0 |CREATE_REG|Manifest: NOSIGNATURE
InsaneLib-1.2.1-mc1.16.5.jar |InsaneLib |insanelib |1.2.1-mc1.16.5 |CREATE_REG|Manifest: NOSIGNATURE
etched-1.1.0-1.16.5-forge.jar |Etched |etched |1.1.0 |CREATE_REG|Manifest: NOSIGNATURE
FastSuite-1.16.4-1.1.1.jar |FastSuite |fastsuite |1.1.1 |CREATE_REG|Manifest: NOSIGNATURE
ravageandcabbage-1.0.0.jar |Ravage & Cabbage |ravageandcabbage |1.0.0 |CREATE_REG|Manifest: NOSIGNATURE
village-employment-1.16.5-1.4.1.jar |Village Employment |village_employment |1.4.1 |CREATE_REG|Manifest: NOSIGNATURE
Placebo-1.16.5-4.6.0.jar |Placebo |placebo |4.6.0 |CREATE_REG|Manifest: NOSIGNATURE
exlineawnings-1.16.5-1.0.jar |Exline's Awnings |exlineawnings |1.16.5-1.0 |CREATE_REG|Manifest: NOSIGNATURE
citadel-1.8.1-1.16.5.jar |Citadel |citadel |1.8.1 |CREATE_REG|Manifest: NOSIGNATURE
alexsmobs-1.12.1.jar |Alex's Mobs |alexsmobs |1.12.1 |CREATE_REG|Manifest: NOSIGNATURE
farmersdelightintegrations-1.16.5-1.2.jar |Farmer's Delight Compats |farmersdelightintegrations |1.16.5-1.2 |CREATE_REG|Manifest: NOSIGNATURE
YungsApi-1.16.4-Forge-12.jar |YUNG's API |yungsapi |1.16.4-Forge-12 |CREATE_REG|Manifest: NOSIGNATURE
decorative_blocks-1.16.4-1.7.2.jar |Decorative Blocks |decorative_blocks |1.7.2 |CREATE_REG|Manifest: NOSIGNATURE
environmental-1.16.5-1.1.0.jar |Environmental |environmental |1.1.0 |CREATE_REG|Manifest: NOSIGNATURE
[1.16.5]-Epic-Knights-Armor-and-Weapons-2.0v.jar |Epic Knights Armor and Weapons|magistuarmory |1.16-1.17 |CREATE_REG|Manifest: NOSIGNATURE
randompatches-2.4.4-forge.jar |RandomPatches |randompatches |2.4.4-forge |CREATE_REG|Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
lazydfu-0.1.3.jar |LazyDFU |lazydfu |0.1.3 |CREATE_REG|Manifest: NOSIGNATURE
starlight-forge-1.0.0-RC2-1.16.5.jar |Starlight |starlight |1.0.0-RC2 |CREATE_REG|Manifest: NOSIGNATURE
PREGE.jar |Concurrent Chunk Management En|c2me |0.1-SNAPSHOT |CREATE_REG|Manifest: NOSIGNATURE
iceandfire-2.1.9-1.16.5-patched.jar |Ice and Fire |iceandfire |2.1.9-1.16.5 |CREATE_REG|Manifest: NOSIGNATURE
catalogue-1.3.0-1.16.5.jar |Catalogue |catalogue |1.3.0 |CREATE_REG|Manifest: NOSIGNATURE
forge-1.16.5-36.2.5-universal.jar |Forge |forge |36.2.5 |CREATE_REG|Manifest: NOSIGNATURE
supplementaries-1.16.5-0.17.1.jar |Supplementaries |supplementaries |1.16.5-0.16.0 |CREATE_REG|Manifest: NOSIGNATURE
MIA_emoji.jar |Made In Abyss Emoji |emojiful |1.16.5-3.8 |CREATE_REG|Manifest: NOSIGNATURE
betterendforge-1.16.5-1.6.2.jar |BetterEnd Forge |betterendforge |1.16.5-1.6.2 |CREATE_REG|Manifest: NOSIGNATURE
Upgraded+Netherite+1.10.0.jar |Upgraded Netherite |upgradednetherite |1.10.0 |CREATE_REG|Manifest: NOSIGNATURE
structure_gel-1.16.5-1.7.7.jar |Structure Gel API |structure_gel |1.7.7 |CREATE_REG|Manifest: NOSIGNATURE
selene-1.16.5-1.7.1.jar |Selene |selene |1.16.5-1.0 |CREATE_REG|Manifest: NHunterIllager-1.16.5-1.4.0.jar |Hunter Illager |hunterillager |1.16.5-1.4.0 |CREATE_REG|Manifest: NOSIGNATURE
OSIGNATURE
DungeonsArise-1.16.5-2.1.47-release.jar |When Dungeons Arise |dungeons_arise |2.1.47 |CREATE_REG|Manifest: NOSIGNATURE
forge-1.16.5-36.2.5-server.jar |Minecraft |minecraft |1.16.5 |CREATE_REG|Manifest: NOSIGNATURE
upgrade_aquatic-1.16.5-3.1.0.jar |Upgrade Aquatic |upgrade_aquatic |3.1.0 |CREATE_REG|Manifest: NOSIGNATURE
FarmersDelight-1.16.5-0.4.6.jar |Farmer's Delight |farmersdelight |1.16.5-0.4.6 |CREATE_REG|Manifest: NOSIGNATURE
DustrialDecor-1.2.8.jar |'Dustrial Decor |dustrial_decor |1.2.8 |CREATE_REG|Manifest: NOSIGNATURE
repurposed_structures_forge-3.2.5+1.16.5.jar |Repurposed Structures |repurposed_structures |3.2.5+1.16.5 |CREATE_REG|Manifest: NOSIGNATURE
morevillagers-FORGE-1.16.5-1.5.5.jar |More Villagers |morevillagers |1.5.5 |CREATE_REG|Manifest: NOSIGNATURE
AIReducer-1.16-0.1.0.jar |AI Reducer |aireducer |0.1.0 |CREATE_REG|Manifest: NOSIGNATURE
Abundance-1.16.5-1.0.5.jar |Abundance |abundance |1.16.5-1.0.5 |CREATE_REG|Manifest: NOSIGNATURE
greekfantasy-16.5.3.jar |Greek Fantasy |greekfantasy |16.5.3 |CREATE_REG|Manifest: NOSIGNATURE
getittogetherdrops-1.16.4-v1.1.jar |Get It Together, Drops! |getittogetherdrops |v1.1 |CREATE_REG|Manifest: NOSIGNATURE
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar |Biomes O' Plenty |biomesoplenty |1.16.5-13.1.0.477 |CREATE_REG|Manifest: NOSIGNATURE
endremastered-forge-R4.1.1.jar |End Remastered |endrem |4.1 |CREATE_REG|Manifest: NOSIGNATURE
astikorcarts-1.16.5-1.1.1.jar |AstikorCarts |astikorcarts |1.1.1 |CREATE_REG|Manifest: NOSIGNATURE
atmospheric-1.16.5-3.1.0.jar |Atmospheric |atmospheric |3.1.0 |CREATE_REG|Manifest: NOSIGNATURE
Bountiful-1.16.4-3.3.1.jar |Bountiful |bountiful |1.16.4-3.3.1 |CREATE_REG|Manifest: NOSIGNATURE
decorative_winter-0.1.2.jar |Decorative Winter |decorative_winter |0.1.2 |CREATE_REG|Manifest: NOSIGNATURE
mostructures-forge-1.2.0-1.16.5.jar |Mo' Structures |mostructures |1.2.0-1.16.5 |CREATE_REG|Manifest: NOSIGNATURE
flywheel-1.16-0.2.3.jar |Flywheel |flywheel |1.16-0.2.3 |CREATE_REG|Manifest: NOSIGNATURE
create-mc1.16.5_v0.3.2d.jar |Create |create |v0.3.2d |CREATE_REG|Manifest: NOSIGNATURE
curios-forge-1.16.5-4.0.5.2.jar |Curios API |curios |1.16.5-4.0.5.2 |CREATE_REG|Manifest: NOSIGNATURE
eidolon-0.3_Made_In_Abyss_Server.jar |Eidolon Made In Abyss Server F|eidolon |0.3 |CREATE_REG|Manifest: NOSIGNATURE
Atum-1.16.5-2.2.7.jar |Atum 2 |atum |1.16.5-2.2.7 |CREATE_REG|Manifest: NOSIGNATURE
omnis-1.16.5-1.1.2.3.jar |Omnis |omnis |1.16.5-1.0 |CREATE_REG|Manifest: NOSIGNATURE
Patchouli-1.16.4-53.1.jar |Patchouli |patchouli |1.16.4-53.1 |CREATE_REG|Manifest: NOSIGNATURE
overworld_two-1.0-Forge-1.16.4.jar |Overworld 2 |overworld_two |1.0 |CREATE_REG|Manifest: NOSIGNATURE
itemblacklist-1.16.5-1.0.1.jar |Item Blacklist |itemblacklist |1.16.5-1.0.1 |CREATE_REG|Manifest: NOSIGNATURE
collective-1.16.5-2.64.jar |Collective |collective |2.64 |CREATE_REG|Manifest: NOSIGNATURE
autumnity-1.16.5-2.1.1.jar |Autumnity |autumnity |2.1.1 |CREATE_REG|Manifest: NOSIGNATURE
AutoRegLib-1.6-49.jar |AutoRegLib |autoreglib |1.6-49 |CREATE_REG|Manifest: NOSIGNATURE
Quark-r2.4-316.jar |Quark |quark |r2.4-316 |CREATE_REG|Manifest: NOSIGNATURE
abnormals_delight-1.16.5-1.2.0.jar |Abnormals Delight |abnormals_delight |1.2.0 |CREATE_REG|Manifest: NOSIGNATURE
performant-1.16.2-5-3.72m.jar |Performant |performant |3.56m |CREATE_REG|Manifest: NOSIGNATURE
DiagonalFences-v1.1.1-1.16.5.jar |Diagonal Fences |diagonalfences |1.1.1 |CREATE_REG|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
DoubleSlabs-1.16-3.7.1.jar |Double Slabs |doubleslabs |3.7.1 |CREATE_REG|Manifest: NOSIGNATURE
simplytea-1.16.5-2.4.0.jar |Simply Tea |simplytea |2.4.0 |CREATE_REG|Manifest: NOSIGNATURE
Desolation+1.1.0-1+1.16.5.jar |Desolation (Forge) |desolation |1.1.0-1 |CREATE_REG|Manifest: NOSIGNATURE
EnigmaticLegacy-2.11.5.jar |Enigmatic Legacy |enigmaticlegacy |2.11.5 |CREATE_REG|Manifest: NOSIGNATURE
ferritecore-2.0.7-forge.jar |Ferrite Core |ferritecore |2.0.7 |CREATE_REG|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a nethers_delight-2.1.jar |Nethers Delight |nethers_delight |2.1 |CREATE_REG|Manifest: NOSIGNATURE
smallships-1.16.5-1.10.1.jar |Small Ships Mod |smallships |1.10.1 |CREATE_REG|Manifest: NOSIGNATURE Crash Report UUID: 6a10a306-e935-47cf-ab2c-121d66824da8
EnhancedAI-Alpha-1.2.0-mc1.16.5.jar |Enhanced AI |enhancedai |Alpha-1.2.0 |ERROR |Manifest: NOSIGNATURE
farmerstea-1.16.5-1.2.jar |Farmer's Tea |farmerstea |1.16.5-1.2 |CREATE_REG|Manifest: NOSIGNATURE

Aquaculture-1.16.5-2.1.21.jar |Aquaculture 2 |aquaculture |1.16.5-2.1.21 |CREATE_REG|Manifest: NOSIGNATURE
createaddition-1.16.5-20210911a.jar |Create Crafts & Additions |createaddition |1.16.5-20210911a |CREATE_REG|Manifest: NOSIGNATUREvalhelsia_core-16.0.10.jar |Valhelsia Core |valhelsia_core |16.0.10 |CREATE_REG|Manifest
: NOSIGNATURE

valhelsia_structures-1.16.5-0.1.5.jar |Valhelsia Structures |valhelsia_structures |1.16.5-0.1.5 |CREATE_REG|Manifest: NOSIGNATURE
Running: BetterMineshafts-Forge-1.16.4-2.0.4.jar |YUNG's Better Mineshafts |bettermineshafts |1.16.4-2.0.4 |CREATE_REG|Manifest: NOSIGNATURE
CraftBukkit Information:

Failed to handle CraftCrashReport: craftbukkit not runs
PuzzlesLib-v1.0.10-1.16.5.jar |Puzzles Lib |puzzleslib |1.0.10 |CREATE_REG|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
[12:02:58][main][FATAL]: Failed to start the minecraft server

**Comment by Insane96** [comment]
Open a new issue following the issue template please.
